yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path(
        '', views.index, name='index'
    ),
    path(
        'group/<slug:slug>/',
        views.group_posts, name='group_list'
    ),
    path(
        'profile/<str:username>/',
        views.profile, name='profile'
    ),
    path(
        'posts/<int:post_id>/',
        views.post_detail, name='post_detail'
    ),
    path(
        'create/', views.post_create,
        name='post_create'
    ),
    path(
        'posts/<int:post_id>/edit/',
        views.post_edit, name='post_edit'
    ),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment, name='add_comment'
    ),
    path(
        'follow/', views.follow_index,
        name='follow_index'
    ),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow, name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow, name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from . import settings

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         path('__debug__/', include(debug_toolbar.urls))
#     ] + urlpatterns

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

from yatube.settings import MAX_CHAR_TITLE

User = get_user_model()


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        verbose_name='Дата публикации',
        auto_now_add=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='posts'
    )
    group = models.ForeignKey(
        'Group',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'
        ordering = ['-pub_date']

    def __str__(self):
        return self.text[:MAX_CHAR_TITLE]


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(null=False, unique=True)
    description = models.TextField()

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(
        'Post',
        verbose_name='Комментарий',
        on_delete=models.CASCADE,
        related_name='comments',
        blank=True,
        null=True,
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='comments',
    )
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Введите текст комментария',
    )
    created = models.DateTimeField(
        verbose_name='Дата публикации комментария',
        auto_now_add=True,
    )

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return self.text


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Подписчик',
        related_name='follower',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='following',
    )

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'

    def __str__(self):
        return f'{self.user} - {self.author}'

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User
from .utils import get_page


@cache_page(20, key_prefix='index_page')
def index(request):
    post_list = Post.objects.all().select_related('group', 'author')
    page_obj = get_page(request, post_list)
    context = {
        'page_obj': page_obj,
        'index': True,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = Post.objects.filter(
        group=group).select_related('group', 'author')
    page_obj = get_page(request, post_list)
    context = {
        'group': group,
        'page_obj': page_obj
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    post_list = Post.objects.filter(
        author_id=author.id).select_related('group')
    page_obj = get_page(request, post_list)
    following = (
        request.user.is_authenticated and request.user.follower.filter(
            author=author).exists())
    context = {
        'author': author,
        'page_obj': page_obj,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    comments = post.comments.all()
    context = {
        'post': post,
        'form': form,
        'comments': comments,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    context = {
        'form': form,
    }
    if form.is_valid():
        post = form.save(False)
        post.author = request.user
        form.save()
        return redirect('posts:profile', request.user)
    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post,
    )
    context = {
        'form': form,
        'is_edit': True
    }
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('posts:post_detail', post_id)
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    post_list = Post.objects.filter(
        author__following__user=request.user).select_related('group', 'author')
    page_obj = get_page(request, post_list)
    context = {
        'page_obj': page_obj,
        'follow': True,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if request.user != author:
        Follow.objects.get_or_create(
            user=request.user,
            author=author,
        )
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=author).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
  {% if is_edit %}
    Редактирование записи
  {% else %}
    Новый пост
  {% endif %} 
{% endblock title %}

{% block content %}
<main>
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">       
            {% if is_edit %}
              Редактировать запись
            {% else %}
              Новый пост
            {% endif %}         
          </div>
          <div class="card-body">
            {% load user_filters %}
            <form method="post" enctype="multipart/form-data">
              {% csrf_token %}
              {% for field in form %}
                <div class="form-group row my-3 p-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                    {% if field.field.required %}
                      <span class="required text-danger">*</span>
                    {% endif %}
                </label>                
                {{ field|addclass:'form-control' }}
                  {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}          
              </div>
              {% endfor %}
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}
                </button>
              </div>
            </form>            
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock content %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
Мои подписки
{% endblock title %}

{% block content %}
{% include 'posts/includes/switcher.html' %}
<main> 
  <div class="container py-5">             
    <h1> Мои подписки </h1>
      {% if not page_obj %}
        Вы ни на кого не подписаны. Чего же вы ждете?!
      {% endif %}
    <article>
  {% for post in page_obj %}
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }} 
        <a href="{% url 'posts:profile' post.author.username %}">
           все посты пользователя
        </a>
        </li>
      <li> Дата публикации: {{ post.pub_date|date:"d E Y" }} </li>
    </ul> 
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p> {{ post.text }} </p>
    {% if post.group %}
      <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    {% endif %}
    <p>
      <a href="{% url 'posts:post_detail' post.id %} ">подробная информация </a>
    </p>
    {% if not forloop.last %} <hr> {% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
    </article>
  </div>  
</main>
{% endblock content %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
Записи сообщества {{ group.title }}
{% endblock title %}

{% block content %}
<main>
  <div class="container py-5">
    <h1> {{ group.title }} </h1>
    <p> {{ group.description }} </p>
    <article>
      {% for post in page_obj %}
        <ul>
          <li> Автор: {{ post.author.get_full_name }}
            <a href="{% url 'posts:profile' post.author.username %}">
              все посты пользователя
           </a>
          </li>
          <li> Дата публикации: {{ post.pub_date|date:"d E Y" }} </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p> {{ post.text }} </p>
        <a href="{% url 'posts:post_detail' post.id %} ">подробная информация </a>
        <p>
          <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
        </p>
        {% if not forloop.last %} <hr> {% endif %}
      {% endfor %}
      {% include 'posts/includes/paginator.html' %}
    </article>
  </div>  
</main>
{% endblock content %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
Последние обновления на сайте
{% endblock title %}

{% block content %}
{% include 'posts/includes/switcher.html' %}
<main> 
  <div class="container py-5">             
    <h1> Последние обновления на сайте </h1>    
    <article>
  {% for post in page_obj %}
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }} 
        <a href="{% url 'posts:profile' post.author.username %}">
           все посты пользователя
        </a>
        </li>
      <li> Дата публикации: {{ post.pub_date|date:"d E Y" }} </li>
    </ul> 
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p> {{ post.text }} </p>
    {% if post.group %}
      <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    {% endif %}
    <p>
      <a href="{% url 'posts:post_detail' post.id %} ">подробная информация </a>
    </p>
    {% if not forloop.last %} <hr> {% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
    </article>
  </div>  
</main>
{% endblock content %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
Пост {{ post.text|slice:":30" }}
{% endblock title %}

{% block content %}
<main>
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
        {% if  post.group %}
        <li class="list-group-item">
          Группа: {{ post.group }}
          <a href="{% url 'posts:group_list' post.group.slug %}">
            все записи группы
          </a>
        </li>
        {% endif %}
        <li class="list-group-item">
          Автор: {{ post.author.get_full_name }}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span > {{ post.author.posts.count }} </span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author.username %}">
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p> {{ post.text }} </p>
      {% if  post.author.id == user.id %}
      <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
        редактировать запись
      </a>
      {% endif %}
      {% include 'posts/includes/add_comment.html' %}
    </article>
  </div> 
</main>
{% endblock content %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
Профайл пользователя {{ author }}
{% endblock title %}

{% block content %}
<main>
  <div class="container py-5">
    <div class="mb-5">
      <h1>Все посты пользователя {{ author.get_full_name }}</h1>
      <h3>Всего постов: {{ author.posts.count }} </h3>
      {% if author != user %}
        {% if following %}
          <a class="btn btn-lg btn-light" href="{% url 'posts:profile_unfollow' author.username %}" role="button">
            Отписаться
          </a>
        {% else %}
          <a class="btn btn-lg btn-primary" href="{% url 'posts:profile_follow' author.username %}" role="button">
            Подписаться
          </a>
        {% endif %}
        </div>
      {% endif%}
    <article>
        {% for post in page_obj %}      
        <ul>
        <li> Автор: {{ author.get_full_name }} </li>            
        <li> Дата публикации: {{ post.pub_date|date:"d E Y" }} </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p> {{ post.text }} </p>
        <a href="{% url 'posts:post_detail' post.id %} ">подробная информация </a>
        </article>
            {% if post.group %}
            <p>
                <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
            </p>
            {% endif %}
            {% if not forloop.last %} <hr> {% endif %}
            {% endfor %}
    {% include 'posts/includes/paginator.html' %}
    </div>
</main>
{% endblock content %}